version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend/
    env_file:
      - ./backend/.local.env
    volumes:
      - .:/backend
      - /backend/node_modules
    ports:
      - "5001:5001"
      - "5002:5002"
    command: ["npm", "start"]
    restart: always
